# Generated by Django 3.2.10 on 2023-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='categoria_manutencao',
            field=models.ManyToManyField(to='servicos.CategoriaManutencao'),
        ),
    ]
